// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.34.0
// source: proto/main.proto

/* eslint-disable */
import type { handleUnaryCall, UntypedServiceImplementation } from '@grpc/grpc-js'
import _m0 from 'protobufjs/minimal.js'

export const protobufPackage = 'proto'

export interface RunCommandRequest {
  additionalInfo: AdditionalInfo | undefined
  args: string[]
  coreCliHelperId: number
}

export interface RunCommandResponse {}

export interface AdditionalInfo {
  isTerminal: IsTerminal | undefined
  terminalDimensions: TerminalDimensions | undefined
}

export interface IsTerminal {
  stdin: boolean
  stdout: boolean
  stderr: boolean
}

export interface TerminalDimensions {
  width: number
  height: number
}

export interface EchoRequest {
  input: string
}

export interface EchoResponse {
  output: string
}

export interface SendAnalyticsRequest {
  eventName: string
  eventValue: string
}

export interface SendAnalyticsResponse {}

export interface KeychainGetPasswordRequest {
  key: string
}

export interface KeychainGetPasswordResponse {
  value: string
  found: boolean
}

export interface KeychainSetPasswordRequest {
  key: string
  value: string
}

export interface KeychainSetPasswordResponse {}

export interface KeychainDeletePasswordRequest {
  key: string
}

export interface KeychainDeletePasswordResponse {
  deleted: boolean
}

export interface KeychainFindCredentialsRequest {}

export interface KeychainFindCredentialsResponse {
  keys: string[]
}

export interface RunPeerPluginRequest {
  pluginName: string
  args: string[]
  cwd: string
}

export interface RunPeerPluginResponse {}

function createBaseRunCommandRequest(): RunCommandRequest {
  return { additionalInfo: undefined, args: [], coreCliHelperId: 0 }
}

export const RunCommandRequest = {
  encode(
    message: RunCommandRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.additionalInfo !== undefined) {
      AdditionalInfo.encode(message.additionalInfo, writer.uint32(10).fork()).ldelim()
    }
    for (const v of message.args) {
      writer.uint32(18).string(v!)
    }
    if (message.coreCliHelperId !== 0) {
      writer.uint32(24).uint32(message.coreCliHelperId)
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RunCommandRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseRunCommandRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break
          }

          message.additionalInfo = AdditionalInfo.decode(reader, reader.uint32())
          continue
        case 2:
          if (tag !== 18) {
            break
          }

          message.args.push(reader.string())
          continue
        case 3:
          if (tag !== 24) {
            break
          }

          message.coreCliHelperId = reader.uint32()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): RunCommandRequest {
    return {
      additionalInfo: isSet(object.additionalInfo)
        ? AdditionalInfo.fromJSON(object.additionalInfo)
        : undefined,
      args: globalThis.Array.isArray(object?.args)
        ? object.args.map((e: any) => globalThis.String(e))
        : [],
      coreCliHelperId: isSet(object.coreCliHelperId)
        ? globalThis.Number(object.coreCliHelperId)
        : 0,
    }
  },

  toJSON(message: RunCommandRequest): unknown {
    const obj: any = {}
    if (message.additionalInfo !== undefined) {
      obj.additionalInfo = AdditionalInfo.toJSON(message.additionalInfo)
    }
    if (message.args?.length) {
      obj.args = message.args
    }
    if (message.coreCliHelperId !== 0) {
      obj.coreCliHelperId = Math.round(message.coreCliHelperId)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<RunCommandRequest>, I>>(
    base?: I,
  ): RunCommandRequest {
    return RunCommandRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<RunCommandRequest>, I>>(
    object: I,
  ): RunCommandRequest {
    const message = createBaseRunCommandRequest()
    message.additionalInfo =
      object.additionalInfo !== undefined && object.additionalInfo !== null
        ? AdditionalInfo.fromPartial(object.additionalInfo)
        : undefined
    message.args = object.args?.map(e => e) || []
    message.coreCliHelperId = object.coreCliHelperId ?? 0
    return message
  },
}

function createBaseRunCommandResponse(): RunCommandResponse {
  return {}
}

export const RunCommandResponse = {
  encode(_: RunCommandResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RunCommandResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseRunCommandResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(_: any): RunCommandResponse {
    return {}
  },

  toJSON(_: RunCommandResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<RunCommandResponse>, I>>(
    base?: I,
  ): RunCommandResponse {
    return RunCommandResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<RunCommandResponse>, I>>(
    _: I,
  ): RunCommandResponse {
    const message = createBaseRunCommandResponse()
    return message
  },
}

function createBaseAdditionalInfo(): AdditionalInfo {
  return { isTerminal: undefined, terminalDimensions: undefined }
}

export const AdditionalInfo = {
  encode(message: AdditionalInfo, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.isTerminal !== undefined) {
      IsTerminal.encode(message.isTerminal, writer.uint32(10).fork()).ldelim()
    }
    if (message.terminalDimensions !== undefined) {
      TerminalDimensions.encode(
        message.terminalDimensions,
        writer.uint32(18).fork(),
      ).ldelim()
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): AdditionalInfo {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseAdditionalInfo()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break
          }

          message.isTerminal = IsTerminal.decode(reader, reader.uint32())
          continue
        case 2:
          if (tag !== 18) {
            break
          }

          message.terminalDimensions = TerminalDimensions.decode(reader, reader.uint32())
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): AdditionalInfo {
    return {
      isTerminal: isSet(object.isTerminal)
        ? IsTerminal.fromJSON(object.isTerminal)
        : undefined,
      terminalDimensions: isSet(object.terminalDimensions)
        ? TerminalDimensions.fromJSON(object.terminalDimensions)
        : undefined,
    }
  },

  toJSON(message: AdditionalInfo): unknown {
    const obj: any = {}
    if (message.isTerminal !== undefined) {
      obj.isTerminal = IsTerminal.toJSON(message.isTerminal)
    }
    if (message.terminalDimensions !== undefined) {
      obj.terminalDimensions = TerminalDimensions.toJSON(message.terminalDimensions)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<AdditionalInfo>, I>>(base?: I): AdditionalInfo {
    return AdditionalInfo.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<AdditionalInfo>, I>>(
    object: I,
  ): AdditionalInfo {
    const message = createBaseAdditionalInfo()
    message.isTerminal =
      object.isTerminal !== undefined && object.isTerminal !== null
        ? IsTerminal.fromPartial(object.isTerminal)
        : undefined
    message.terminalDimensions =
      object.terminalDimensions !== undefined && object.terminalDimensions !== null
        ? TerminalDimensions.fromPartial(object.terminalDimensions)
        : undefined
    return message
  },
}

function createBaseIsTerminal(): IsTerminal {
  return { stdin: false, stdout: false, stderr: false }
}

export const IsTerminal = {
  encode(message: IsTerminal, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.stdin !== false) {
      writer.uint32(8).bool(message.stdin)
    }
    if (message.stdout !== false) {
      writer.uint32(16).bool(message.stdout)
    }
    if (message.stderr !== false) {
      writer.uint32(24).bool(message.stderr)
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): IsTerminal {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseIsTerminal()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break
          }

          message.stdin = reader.bool()
          continue
        case 2:
          if (tag !== 16) {
            break
          }

          message.stdout = reader.bool()
          continue
        case 3:
          if (tag !== 24) {
            break
          }

          message.stderr = reader.bool()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): IsTerminal {
    return {
      stdin: isSet(object.stdin) ? globalThis.Boolean(object.stdin) : false,
      stdout: isSet(object.stdout) ? globalThis.Boolean(object.stdout) : false,
      stderr: isSet(object.stderr) ? globalThis.Boolean(object.stderr) : false,
    }
  },

  toJSON(message: IsTerminal): unknown {
    const obj: any = {}
    if (message.stdin !== false) {
      obj.stdin = message.stdin
    }
    if (message.stdout !== false) {
      obj.stdout = message.stdout
    }
    if (message.stderr !== false) {
      obj.stderr = message.stderr
    }
    return obj
  },

  create<I extends Exact<DeepPartial<IsTerminal>, I>>(base?: I): IsTerminal {
    return IsTerminal.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<IsTerminal>, I>>(object: I): IsTerminal {
    const message = createBaseIsTerminal()
    message.stdin = object.stdin ?? false
    message.stdout = object.stdout ?? false
    message.stderr = object.stderr ?? false
    return message
  },
}

function createBaseTerminalDimensions(): TerminalDimensions {
  return { width: 0, height: 0 }
}

export const TerminalDimensions = {
  encode(
    message: TerminalDimensions,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.width !== 0) {
      writer.uint32(8).uint32(message.width)
    }
    if (message.height !== 0) {
      writer.uint32(16).uint32(message.height)
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TerminalDimensions {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseTerminalDimensions()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break
          }

          message.width = reader.uint32()
          continue
        case 2:
          if (tag !== 16) {
            break
          }

          message.height = reader.uint32()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): TerminalDimensions {
    return {
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
    }
  },

  toJSON(message: TerminalDimensions): unknown {
    const obj: any = {}
    if (message.width !== 0) {
      obj.width = Math.round(message.width)
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<TerminalDimensions>, I>>(
    base?: I,
  ): TerminalDimensions {
    return TerminalDimensions.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<TerminalDimensions>, I>>(
    object: I,
  ): TerminalDimensions {
    const message = createBaseTerminalDimensions()
    message.width = object.width ?? 0
    message.height = object.height ?? 0
    return message
  },
}

function createBaseEchoRequest(): EchoRequest {
  return { input: '' }
}

export const EchoRequest = {
  encode(message: EchoRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.input !== '') {
      writer.uint32(10).string(message.input)
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EchoRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseEchoRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break
          }

          message.input = reader.string()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): EchoRequest {
    return { input: isSet(object.input) ? globalThis.String(object.input) : '' }
  },

  toJSON(message: EchoRequest): unknown {
    const obj: any = {}
    if (message.input !== '') {
      obj.input = message.input
    }
    return obj
  },

  create<I extends Exact<DeepPartial<EchoRequest>, I>>(base?: I): EchoRequest {
    return EchoRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<EchoRequest>, I>>(object: I): EchoRequest {
    const message = createBaseEchoRequest()
    message.input = object.input ?? ''
    return message
  },
}

function createBaseEchoResponse(): EchoResponse {
  return { output: '' }
}

export const EchoResponse = {
  encode(message: EchoResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.output !== '') {
      writer.uint32(10).string(message.output)
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EchoResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseEchoResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break
          }

          message.output = reader.string()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): EchoResponse {
    return { output: isSet(object.output) ? globalThis.String(object.output) : '' }
  },

  toJSON(message: EchoResponse): unknown {
    const obj: any = {}
    if (message.output !== '') {
      obj.output = message.output
    }
    return obj
  },

  create<I extends Exact<DeepPartial<EchoResponse>, I>>(base?: I): EchoResponse {
    return EchoResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<EchoResponse>, I>>(object: I): EchoResponse {
    const message = createBaseEchoResponse()
    message.output = object.output ?? ''
    return message
  },
}

function createBaseSendAnalyticsRequest(): SendAnalyticsRequest {
  return { eventName: '', eventValue: '' }
}

export const SendAnalyticsRequest = {
  encode(
    message: SendAnalyticsRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.eventName !== '') {
      writer.uint32(10).string(message.eventName)
    }
    if (message.eventValue !== '') {
      writer.uint32(18).string(message.eventValue)
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SendAnalyticsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseSendAnalyticsRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break
          }

          message.eventName = reader.string()
          continue
        case 2:
          if (tag !== 18) {
            break
          }

          message.eventValue = reader.string()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): SendAnalyticsRequest {
    return {
      eventName: isSet(object.eventName) ? globalThis.String(object.eventName) : '',
      eventValue: isSet(object.eventValue) ? globalThis.String(object.eventValue) : '',
    }
  },

  toJSON(message: SendAnalyticsRequest): unknown {
    const obj: any = {}
    if (message.eventName !== '') {
      obj.eventName = message.eventName
    }
    if (message.eventValue !== '') {
      obj.eventValue = message.eventValue
    }
    return obj
  },

  create<I extends Exact<DeepPartial<SendAnalyticsRequest>, I>>(
    base?: I,
  ): SendAnalyticsRequest {
    return SendAnalyticsRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<SendAnalyticsRequest>, I>>(
    object: I,
  ): SendAnalyticsRequest {
    const message = createBaseSendAnalyticsRequest()
    message.eventName = object.eventName ?? ''
    message.eventValue = object.eventValue ?? ''
    return message
  },
}

function createBaseSendAnalyticsResponse(): SendAnalyticsResponse {
  return {}
}

export const SendAnalyticsResponse = {
  encode(_: SendAnalyticsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SendAnalyticsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseSendAnalyticsResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(_: any): SendAnalyticsResponse {
    return {}
  },

  toJSON(_: SendAnalyticsResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<SendAnalyticsResponse>, I>>(
    base?: I,
  ): SendAnalyticsResponse {
    return SendAnalyticsResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<SendAnalyticsResponse>, I>>(
    _: I,
  ): SendAnalyticsResponse {
    const message = createBaseSendAnalyticsResponse()
    return message
  },
}

function createBaseKeychainGetPasswordRequest(): KeychainGetPasswordRequest {
  return { key: '' }
}

export const KeychainGetPasswordRequest = {
  encode(
    message: KeychainGetPasswordRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.key !== '') {
      writer.uint32(10).string(message.key)
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KeychainGetPasswordRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseKeychainGetPasswordRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break
          }

          message.key = reader.string()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): KeychainGetPasswordRequest {
    return { key: isSet(object.key) ? globalThis.String(object.key) : '' }
  },

  toJSON(message: KeychainGetPasswordRequest): unknown {
    const obj: any = {}
    if (message.key !== '') {
      obj.key = message.key
    }
    return obj
  },

  create<I extends Exact<DeepPartial<KeychainGetPasswordRequest>, I>>(
    base?: I,
  ): KeychainGetPasswordRequest {
    return KeychainGetPasswordRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<KeychainGetPasswordRequest>, I>>(
    object: I,
  ): KeychainGetPasswordRequest {
    const message = createBaseKeychainGetPasswordRequest()
    message.key = object.key ?? ''
    return message
  },
}

function createBaseKeychainGetPasswordResponse(): KeychainGetPasswordResponse {
  return { value: '', found: false }
}

export const KeychainGetPasswordResponse = {
  encode(
    message: KeychainGetPasswordResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.value !== '') {
      writer.uint32(10).string(message.value)
    }
    if (message.found !== false) {
      writer.uint32(16).bool(message.found)
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KeychainGetPasswordResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseKeychainGetPasswordResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break
          }

          message.value = reader.string()
          continue
        case 2:
          if (tag !== 16) {
            break
          }

          message.found = reader.bool()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): KeychainGetPasswordResponse {
    return {
      value: isSet(object.value) ? globalThis.String(object.value) : '',
      found: isSet(object.found) ? globalThis.Boolean(object.found) : false,
    }
  },

  toJSON(message: KeychainGetPasswordResponse): unknown {
    const obj: any = {}
    if (message.value !== '') {
      obj.value = message.value
    }
    if (message.found !== false) {
      obj.found = message.found
    }
    return obj
  },

  create<I extends Exact<DeepPartial<KeychainGetPasswordResponse>, I>>(
    base?: I,
  ): KeychainGetPasswordResponse {
    return KeychainGetPasswordResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<KeychainGetPasswordResponse>, I>>(
    object: I,
  ): KeychainGetPasswordResponse {
    const message = createBaseKeychainGetPasswordResponse()
    message.value = object.value ?? ''
    message.found = object.found ?? false
    return message
  },
}

function createBaseKeychainSetPasswordRequest(): KeychainSetPasswordRequest {
  return { key: '', value: '' }
}

export const KeychainSetPasswordRequest = {
  encode(
    message: KeychainSetPasswordRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.key !== '') {
      writer.uint32(10).string(message.key)
    }
    if (message.value !== '') {
      writer.uint32(18).string(message.value)
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KeychainSetPasswordRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseKeychainSetPasswordRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break
          }

          message.key = reader.string()
          continue
        case 2:
          if (tag !== 18) {
            break
          }

          message.value = reader.string()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): KeychainSetPasswordRequest {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : '',
      value: isSet(object.value) ? globalThis.String(object.value) : '',
    }
  },

  toJSON(message: KeychainSetPasswordRequest): unknown {
    const obj: any = {}
    if (message.key !== '') {
      obj.key = message.key
    }
    if (message.value !== '') {
      obj.value = message.value
    }
    return obj
  },

  create<I extends Exact<DeepPartial<KeychainSetPasswordRequest>, I>>(
    base?: I,
  ): KeychainSetPasswordRequest {
    return KeychainSetPasswordRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<KeychainSetPasswordRequest>, I>>(
    object: I,
  ): KeychainSetPasswordRequest {
    const message = createBaseKeychainSetPasswordRequest()
    message.key = object.key ?? ''
    message.value = object.value ?? ''
    return message
  },
}

function createBaseKeychainSetPasswordResponse(): KeychainSetPasswordResponse {
  return {}
}

export const KeychainSetPasswordResponse = {
  encode(
    _: KeychainSetPasswordResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KeychainSetPasswordResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseKeychainSetPasswordResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(_: any): KeychainSetPasswordResponse {
    return {}
  },

  toJSON(_: KeychainSetPasswordResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<KeychainSetPasswordResponse>, I>>(
    base?: I,
  ): KeychainSetPasswordResponse {
    return KeychainSetPasswordResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<KeychainSetPasswordResponse>, I>>(
    _: I,
  ): KeychainSetPasswordResponse {
    const message = createBaseKeychainSetPasswordResponse()
    return message
  },
}

function createBaseKeychainDeletePasswordRequest(): KeychainDeletePasswordRequest {
  return { key: '' }
}

export const KeychainDeletePasswordRequest = {
  encode(
    message: KeychainDeletePasswordRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.key !== '') {
      writer.uint32(10).string(message.key)
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): KeychainDeletePasswordRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseKeychainDeletePasswordRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break
          }

          message.key = reader.string()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): KeychainDeletePasswordRequest {
    return { key: isSet(object.key) ? globalThis.String(object.key) : '' }
  },

  toJSON(message: KeychainDeletePasswordRequest): unknown {
    const obj: any = {}
    if (message.key !== '') {
      obj.key = message.key
    }
    return obj
  },

  create<I extends Exact<DeepPartial<KeychainDeletePasswordRequest>, I>>(
    base?: I,
  ): KeychainDeletePasswordRequest {
    return KeychainDeletePasswordRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<KeychainDeletePasswordRequest>, I>>(
    object: I,
  ): KeychainDeletePasswordRequest {
    const message = createBaseKeychainDeletePasswordRequest()
    message.key = object.key ?? ''
    return message
  },
}

function createBaseKeychainDeletePasswordResponse(): KeychainDeletePasswordResponse {
  return { deleted: false }
}

export const KeychainDeletePasswordResponse = {
  encode(
    message: KeychainDeletePasswordResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.deleted !== false) {
      writer.uint32(8).bool(message.deleted)
    }
    return writer
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): KeychainDeletePasswordResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseKeychainDeletePasswordResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break
          }

          message.deleted = reader.bool()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): KeychainDeletePasswordResponse {
    return { deleted: isSet(object.deleted) ? globalThis.Boolean(object.deleted) : false }
  },

  toJSON(message: KeychainDeletePasswordResponse): unknown {
    const obj: any = {}
    if (message.deleted !== false) {
      obj.deleted = message.deleted
    }
    return obj
  },

  create<I extends Exact<DeepPartial<KeychainDeletePasswordResponse>, I>>(
    base?: I,
  ): KeychainDeletePasswordResponse {
    return KeychainDeletePasswordResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<KeychainDeletePasswordResponse>, I>>(
    object: I,
  ): KeychainDeletePasswordResponse {
    const message = createBaseKeychainDeletePasswordResponse()
    message.deleted = object.deleted ?? false
    return message
  },
}

function createBaseKeychainFindCredentialsRequest(): KeychainFindCredentialsRequest {
  return {}
}

export const KeychainFindCredentialsRequest = {
  encode(
    _: KeychainFindCredentialsRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    return writer
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): KeychainFindCredentialsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseKeychainFindCredentialsRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(_: any): KeychainFindCredentialsRequest {
    return {}
  },

  toJSON(_: KeychainFindCredentialsRequest): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<KeychainFindCredentialsRequest>, I>>(
    base?: I,
  ): KeychainFindCredentialsRequest {
    return KeychainFindCredentialsRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<KeychainFindCredentialsRequest>, I>>(
    _: I,
  ): KeychainFindCredentialsRequest {
    const message = createBaseKeychainFindCredentialsRequest()
    return message
  },
}

function createBaseKeychainFindCredentialsResponse(): KeychainFindCredentialsResponse {
  return { keys: [] }
}

export const KeychainFindCredentialsResponse = {
  encode(
    message: KeychainFindCredentialsResponse,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    for (const v of message.keys) {
      writer.uint32(10).string(v!)
    }
    return writer
  },

  decode(
    input: _m0.Reader | Uint8Array,
    length?: number,
  ): KeychainFindCredentialsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseKeychainFindCredentialsResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break
          }

          message.keys.push(reader.string())
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): KeychainFindCredentialsResponse {
    return {
      keys: globalThis.Array.isArray(object?.keys)
        ? object.keys.map((e: any) => globalThis.String(e))
        : [],
    }
  },

  toJSON(message: KeychainFindCredentialsResponse): unknown {
    const obj: any = {}
    if (message.keys?.length) {
      obj.keys = message.keys
    }
    return obj
  },

  create<I extends Exact<DeepPartial<KeychainFindCredentialsResponse>, I>>(
    base?: I,
  ): KeychainFindCredentialsResponse {
    return KeychainFindCredentialsResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<KeychainFindCredentialsResponse>, I>>(
    object: I,
  ): KeychainFindCredentialsResponse {
    const message = createBaseKeychainFindCredentialsResponse()
    message.keys = object.keys?.map(e => e) || []
    return message
  },
}

function createBaseRunPeerPluginRequest(): RunPeerPluginRequest {
  return { pluginName: '', args: [], cwd: '' }
}

export const RunPeerPluginRequest = {
  encode(
    message: RunPeerPluginRequest,
    writer: _m0.Writer = _m0.Writer.create(),
  ): _m0.Writer {
    if (message.pluginName !== '') {
      writer.uint32(10).string(message.pluginName)
    }
    for (const v of message.args) {
      writer.uint32(18).string(v!)
    }
    if (message.cwd !== '') {
      writer.uint32(26).string(message.cwd)
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RunPeerPluginRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseRunPeerPluginRequest()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break
          }

          message.pluginName = reader.string()
          continue
        case 2:
          if (tag !== 18) {
            break
          }

          message.args.push(reader.string())
          continue
        case 3:
          if (tag !== 26) {
            break
          }

          message.cwd = reader.string()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): RunPeerPluginRequest {
    return {
      pluginName: isSet(object.pluginName) ? globalThis.String(object.pluginName) : '',
      args: globalThis.Array.isArray(object?.args)
        ? object.args.map((e: any) => globalThis.String(e))
        : [],
      cwd: isSet(object.cwd) ? globalThis.String(object.cwd) : '',
    }
  },

  toJSON(message: RunPeerPluginRequest): unknown {
    const obj: any = {}
    if (message.pluginName !== '') {
      obj.pluginName = message.pluginName
    }
    if (message.args?.length) {
      obj.args = message.args
    }
    if (message.cwd !== '') {
      obj.cwd = message.cwd
    }
    return obj
  },

  create<I extends Exact<DeepPartial<RunPeerPluginRequest>, I>>(
    base?: I,
  ): RunPeerPluginRequest {
    return RunPeerPluginRequest.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<RunPeerPluginRequest>, I>>(
    object: I,
  ): RunPeerPluginRequest {
    const message = createBaseRunPeerPluginRequest()
    message.pluginName = object.pluginName ?? ''
    message.args = object.args?.map(e => e) || []
    message.cwd = object.cwd ?? ''
    return message
  },
}

function createBaseRunPeerPluginResponse(): RunPeerPluginResponse {
  return {}
}

export const RunPeerPluginResponse = {
  encode(_: RunPeerPluginResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): RunPeerPluginResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseRunPeerPluginResponse()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(_: any): RunPeerPluginResponse {
    return {}
  },

  toJSON(_: RunPeerPluginResponse): unknown {
    const obj: any = {}
    return obj
  },

  create<I extends Exact<DeepPartial<RunPeerPluginResponse>, I>>(
    base?: I,
  ): RunPeerPluginResponse {
    return RunPeerPluginResponse.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<RunPeerPluginResponse>, I>>(
    _: I,
  ): RunPeerPluginResponse {
    const message = createBaseRunPeerPluginResponse()
    return message
  },
}

export type MainService = typeof MainService
export const MainService = {
  runCommand: {
    path: '/proto.Main/RunCommand',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RunCommandRequest) =>
      Buffer.from(RunCommandRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => RunCommandRequest.decode(value),
    responseSerialize: (value: RunCommandResponse) =>
      Buffer.from(RunCommandResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => RunCommandResponse.decode(value),
  },
} as const

export interface MainServer extends UntypedServiceImplementation {
  runCommand: handleUnaryCall<RunCommandRequest, RunCommandResponse>
}

export type CoreCLIHelperService = typeof CoreCLIHelperService
export const CoreCLIHelperService = {
  echo: {
    path: '/proto.CoreCLIHelper/Echo',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: EchoRequest) =>
      Buffer.from(EchoRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => EchoRequest.decode(value),
    responseSerialize: (value: EchoResponse) =>
      Buffer.from(EchoResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => EchoResponse.decode(value),
  },
  sendAnalytics: {
    path: '/proto.CoreCLIHelper/SendAnalytics',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SendAnalyticsRequest) =>
      Buffer.from(SendAnalyticsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => SendAnalyticsRequest.decode(value),
    responseSerialize: (value: SendAnalyticsResponse) =>
      Buffer.from(SendAnalyticsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => SendAnalyticsResponse.decode(value),
  },
  keychainGetPassword: {
    path: '/proto.CoreCLIHelper/KeychainGetPassword',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: KeychainGetPasswordRequest) =>
      Buffer.from(KeychainGetPasswordRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => KeychainGetPasswordRequest.decode(value),
    responseSerialize: (value: KeychainGetPasswordResponse) =>
      Buffer.from(KeychainGetPasswordResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => KeychainGetPasswordResponse.decode(value),
  },
  keychainSetPassword: {
    path: '/proto.CoreCLIHelper/KeychainSetPassword',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: KeychainSetPasswordRequest) =>
      Buffer.from(KeychainSetPasswordRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => KeychainSetPasswordRequest.decode(value),
    responseSerialize: (value: KeychainSetPasswordResponse) =>
      Buffer.from(KeychainSetPasswordResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => KeychainSetPasswordResponse.decode(value),
  },
  keychainDeletePassword: {
    path: '/proto.CoreCLIHelper/KeychainDeletePassword',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: KeychainDeletePasswordRequest) =>
      Buffer.from(KeychainDeletePasswordRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => KeychainDeletePasswordRequest.decode(value),
    responseSerialize: (value: KeychainDeletePasswordResponse) =>
      Buffer.from(KeychainDeletePasswordResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => KeychainDeletePasswordResponse.decode(value),
  },
  keychainFindCredentials: {
    path: '/proto.CoreCLIHelper/KeychainFindCredentials',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: KeychainFindCredentialsRequest) =>
      Buffer.from(KeychainFindCredentialsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => KeychainFindCredentialsRequest.decode(value),
    responseSerialize: (value: KeychainFindCredentialsResponse) =>
      Buffer.from(KeychainFindCredentialsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => KeychainFindCredentialsResponse.decode(value),
  },
  runPeerPlugin: {
    path: '/proto.CoreCLIHelper/RunPeerPlugin',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RunPeerPluginRequest) =>
      Buffer.from(RunPeerPluginRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => RunPeerPluginRequest.decode(value),
    responseSerialize: (value: RunPeerPluginResponse) =>
      Buffer.from(RunPeerPluginResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => RunPeerPluginResponse.decode(value),
  },
} as const

export interface CoreCLIHelperServer extends UntypedServiceImplementation {
  echo: handleUnaryCall<EchoRequest, EchoResponse>
  sendAnalytics: handleUnaryCall<SendAnalyticsRequest, SendAnalyticsResponse>
  keychainGetPassword: handleUnaryCall<
    KeychainGetPasswordRequest,
    KeychainGetPasswordResponse
  >
  keychainSetPassword: handleUnaryCall<
    KeychainSetPasswordRequest,
    KeychainSetPasswordResponse
  >
  keychainDeletePassword: handleUnaryCall<
    KeychainDeletePasswordRequest,
    KeychainDeletePasswordResponse
  >
  keychainFindCredentials: handleUnaryCall<
    KeychainFindCredentialsRequest,
    KeychainFindCredentialsResponse
  >
  runPeerPlugin: handleUnaryCall<RunPeerPluginRequest, RunPeerPluginResponse>
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never
    }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}
