// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v7.34.0
// source: plugin/grpc_stdio.proto

/* eslint-disable */
import {
  handleServerStreamingCall,
  type UntypedServiceImplementation,
} from '@grpc/grpc-js'
import _m0 from 'protobufjs/minimal.js'
import { Empty } from '../google/protobuf/empty.js'

export const protobufPackage = 'plugin'

/**
 * StdioData is a single chunk of stdout or stderr data that is streamed
 * from GRPCStdio.
 */
export interface StdioData {
  channel: StdioData_Channel
  data: Uint8Array
}

export enum StdioData_Channel {
  INVALID = 0,
  STDOUT = 1,
  STDERR = 2,
  UNRECOGNIZED = -1,
}

export function stdioData_ChannelFromJSON(object: any): StdioData_Channel {
  switch (object) {
    case 0:
    case 'INVALID':
      return StdioData_Channel.INVALID
    case 1:
    case 'STDOUT':
      return StdioData_Channel.STDOUT
    case 2:
    case 'STDERR':
      return StdioData_Channel.STDERR
    case -1:
    case 'UNRECOGNIZED':
    default:
      return StdioData_Channel.UNRECOGNIZED
  }
}

export function stdioData_ChannelToJSON(object: StdioData_Channel): string {
  switch (object) {
    case StdioData_Channel.INVALID:
      return 'INVALID'
    case StdioData_Channel.STDOUT:
      return 'STDOUT'
    case StdioData_Channel.STDERR:
      return 'STDERR'
    case StdioData_Channel.UNRECOGNIZED:
    default:
      return 'UNRECOGNIZED'
  }
}

function createBaseStdioData(): StdioData {
  return { channel: 0, data: new Uint8Array(0) }
}

export const StdioData = {
  encode(message: StdioData, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.channel !== 0) {
      writer.uint32(8).int32(message.channel)
    }
    if (message.data.length !== 0) {
      writer.uint32(18).bytes(message.data)
    }
    return writer
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): StdioData {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input)
    let end = length === undefined ? reader.len : reader.pos + length
    const message = createBaseStdioData()
    while (reader.pos < end) {
      const tag = reader.uint32()
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break
          }

          message.channel = reader.int32() as any
          continue
        case 2:
          if (tag !== 18) {
            break
          }

          message.data = reader.bytes()
          continue
      }
      if ((tag & 7) === 4 || tag === 0) {
        break
      }
      reader.skipType(tag & 7)
    }
    return message
  },

  fromJSON(object: any): StdioData {
    return {
      channel: isSet(object.channel) ? stdioData_ChannelFromJSON(object.channel) : 0,
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
    }
  },

  toJSON(message: StdioData): unknown {
    const obj: any = {}
    if (message.channel !== 0) {
      obj.channel = stdioData_ChannelToJSON(message.channel)
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data)
    }
    return obj
  },

  create<I extends Exact<DeepPartial<StdioData>, I>>(base?: I): StdioData {
    return StdioData.fromPartial(base ?? ({} as any))
  },
  fromPartial<I extends Exact<DeepPartial<StdioData>, I>>(object: I): StdioData {
    const message = createBaseStdioData()
    message.channel = object.channel ?? 0
    message.data = object.data ?? new Uint8Array(0)
    return message
  },
}

/**
 * GRPCStdio is a service that is automatically run by the plugin process
 * to stream any stdout/err data so that it can be mirrored on the plugin
 * host side.
 */
export type GRPCStdioService = typeof GRPCStdioService
export const GRPCStdioService = {
  /**
   * StreamStdio returns a stream that contains all the stdout/stderr.
   * This RPC endpoint must only be called ONCE. Once stdio data is consumed
   * it is not sent again.
   *
   * Callers should connect early to prevent blocking on the plugin process.
   */
  streamStdio: {
    path: '/plugin.GRPCStdio/StreamStdio',
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer) => Empty.decode(value),
    responseSerialize: (value: StdioData) =>
      Buffer.from(StdioData.encode(value).finish()),
    responseDeserialize: (value: Buffer) => StdioData.decode(value),
  },
} as const

export interface GRPCStdioServer extends UntypedServiceImplementation {
  /**
   * StreamStdio returns a stream that contains all the stdout/stderr.
   * This RPC endpoint must only be called ONCE. Once stdio data is consumed
   * it is not sent again.
   *
   * Callers should connect early to prevent blocking on the plugin process.
   */
  streamStdio: handleServerStreamingCall<Empty, StdioData>
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, 'base64'))
  } else {
    const bin = globalThis.atob(b64)
    const arr = new Uint8Array(bin.length)
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i)
    }
    return arr
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString('base64')
  } else {
    const bin: string[] = []
    arr.forEach(byte => {
      bin.push(globalThis.String.fromCharCode(byte))
    })
    return globalThis.btoa(bin.join(''))
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>

type KeysOfUnion<T> = T extends T ? keyof T : never
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never
    }

function isSet(value: any): boolean {
  return value !== null && value !== undefined
}
