#!/usr/bin/env bash
# Generates dist/bun-compile-entrypoint.js — the Bun compile entrypoint that embeds
# all declared assets directly into the binary.
#
# This script reads `bun.assets` glob patterns from the plugin's package.json,
# expands them, and writes a JS module that:
#   1. Imports each file with `{ type: "file" }` (tells Bun to embed it)
#   2. Sets globalThis.__EMBEDDED_ASSET_MANIFEST__ mapping logical paths → imports
#   3. Re-exports the esbuild bundle (dist/bundle.js) as the main module
#
# The generated file is only consumed by `bun build --compile`. esbuild never
# sees it (esbuild doesn't support import attributes).
#
# Usage: stripe-cli-generate-embedded-manifest
#        (run from the plugin root, after `pnpm build` produces dist/bundle.js)
#
# Requires: Bun (already a hard dependency of stripe-cli-build-binaries)

set -euo pipefail

if ! command -v bun >/dev/null 2>&1; then
  echo "ERROR: 'bun' not found on PATH. Bun is required to generate the embedded manifest." >&2
  exit 1
fi

if [ ! -f "package.json" ]; then
  echo "ERROR: No package.json found in current directory." >&2
  exit 1
fi

if [ ! -f "dist/bundle.js" ]; then
  echo "ERROR: dist/bundle.js not found. Run the build step first." >&2
  exit 1
fi

OUTPUT="dist/bun-compile-entrypoint.js"

OUTPUT="$OUTPUT" bun -e '
const fs = require("fs");
const path = require("path");

const cwd = process.cwd();
const outputRel = process.env.OUTPUT;
const outputAbs = path.join(cwd, outputRel);
const pkg = JSON.parse(fs.readFileSync(path.join(cwd, "package.json"), "utf8"));
const patterns = pkg.bun?.assets;

if (!patterns || !Array.isArray(patterns) || patterns.length === 0) {
  if (fs.existsSync(outputAbs)) {
    fs.unlinkSync(outputAbs);
    console.log(`Removed stale ${outputRel} (no bun.assets declared)`);
  } else {
    console.log("No bun.assets patterns in package.json — skipping manifest generation");
  }
  process.exit(0);
}

const files = [];
for (const pattern of patterns) {
  const glob = new Bun.Glob(pattern);
  const matched = [...glob.scanSync({ cwd, onlyFiles: true, dot: false })];
  if (matched.length === 0) {
    console.error(`ERROR: asset pattern matched no files: ${pattern}`);
    console.error(`       (evaluated relative to ${cwd})`);
    process.exit(1);
  }
  files.push(...matched);
}

files.sort();

const lines = [
  "// Auto-generated by stripe-cli-generate-embedded-manifest — do not edit",
  "// Bun compile entrypoint: embeds assets and re-exports the esbuild bundle.",
  "",
];

const importNames = [];
for (let i = 0; i < files.length; i++) {
  const name = `_a${i}`;
  importNames.push(name);
  // Paths are relative to dist/ (where this file lives)
  const relPath = "../" + files[i];
  lines.push(`import ${name} from ${JSON.stringify(relPath)} with { type: "file" };`);
}

lines.push("");
lines.push("globalThis.__EMBEDDED_ASSET_MANIFEST__ = {");
for (let i = 0; i < files.length; i++) {
  const comma = i < files.length - 1 ? "," : "";
  lines.push(`  ${JSON.stringify(files[i])}: ${importNames[i]}${comma}`);
}
lines.push("};");
lines.push("");
lines.push("await import(\"./bundle.js\");");
lines.push("");

fs.mkdirSync(path.dirname(outputAbs), { recursive: true });
fs.writeFileSync(outputAbs, lines.join("\n"));
console.log(`Generated ${outputAbs} (${files.length} embedded assets from ${patterns.length} pattern(s))`);
'

